# Generated by Django 5.1.4 on 2024-12-12 18:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("country", models.CharField(choices=[("BR", "Brazil")], max_length=2)),
                ("state", models.CharField(max_length=128)),
                ("city", models.CharField(max_length=128)),
                ("postal_code", models.CharField(max_length=32)),
                ("address", models.CharField(max_length=128)),
                ("number", models.CharField(max_length=32)),
                ("additional_info", models.CharField(blank=True, max_length=128)),
            ],
            options={
                "verbose_name_plural": "Addresses",
            },
        ),
    ]
