version: "3"

services:
  api:
    build:
      context: ../
      dockerfile: docker/${ENVIRONMENT:-local}.dockerfile
      args:
        ENVIRONMENT: ${ENVIRONMENT:-local}
    ports:
      - "8000:8000"
    volumes:
      - ../src:/app
    depends_on:
      - postgres
      - redis
    env_file:
      - ../.env

  postgres:
    image: postgres:16.0
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery-worker:
    build:
      context: ../
      dockerfile: docker/${ENVIRONMENT:-local}.dockerfile
      args:
        ENVIRONMENT: ${ENVIRONMENT:-local}
    command: celery -A api worker --loglevel=info
    volumes:
      - ../src:/app
    depends_on:
      - redis
      - postgres
    env_file:
      - ../.env

  celery-beat:
    build:
      context: ../
      dockerfile: docker/${ENVIRONMENT:-local}.dockerfile
      args:
        ENVIRONMENT: ${ENVIRONMENT:-local}
    command: celery -A api beat --loglevel=info
    volumes:
      - ../src:/app
    depends_on:
      - redis
      - postgres
    env_file:
      - ../.env

volumes:
  postgres_data:
